services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecomdb
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: P@ss1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
